// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParadisePlanner.Infrastructure.Data;

#nullable disable

namespace ParadisePlanner.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250718065449_AddNewResortNo")]
    partial class AddNewResortNo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParadisePlanner.Domain.Entities.Resort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupancy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Resorts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 7, 18, 11, 54, 49, 220, DateTimeKind.Local).AddTicks(6510),
                            Description = "A tranquil retreat bathed in golden sunlight year-round, surrounded by cascading springs and whispering palms.",
                            ImageUrl = "/images/resort1.jpg",
                            Name = "Solstice Haven",
                            Occupancy = "9",
                            Price = 13800000.0,
                            Sqft = 23000
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 7, 18, 11, 54, 49, 220, DateTimeKind.Local).AddTicks(6524),
                            Description = "An island sanctuary encircled by sapphire lagoons and blooming flora, offering the essence of tropical eternity.",
                            ImageUrl = "/images/resort2.jpg",
                            Name = "Azure Elysium",
                            Occupancy = "5",
                            Price = 14900000.0,
                            Sqft = 25000
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 7, 18, 11, 54, 49, 220, DateTimeKind.Local).AddTicks(6526),
                            Description = "A cloud-piercing summit lodge where glass observatories open to panoramic starfields and northern lights.",
                            ImageUrl = "/images/resort3.jpg",
                            Name = "Celestara Peak",
                            Occupancy = "5",
                            Price = 15700000.0,
                            Sqft = 28000
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 7, 18, 11, 54, 49, 220, DateTimeKind.Local).AddTicks(6528),
                            Description = "Hidden deep within a rainforest, this eco-luxury resort features glowing waterfalls and mineral-rich lagoons.",
                            ImageUrl = "/images/resort4.jpg",
                            Name = "Luminar Springs",
                            Occupancy = "8",
                            Price = 12400000.0,
                            Sqft = 20000
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 7, 18, 11, 54, 49, 220, DateTimeKind.Local).AddTicks(6529),
                            Description = "A celestial coastal escape where white sand meets diamond-clear water, kissed by heavenly breezes.",
                            ImageUrl = "/images/resort5.jpg",
                            Name = "Seraphine Bay",
                            Occupancy = "9",
                            Price = 14200000.0,
                            Sqft = 24000
                        });
                });

            modelBuilder.Entity("ParadisePlanner.Domain.Entities.ResortNo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ResortId")
                        .HasColumnType("int");

                    b.Property<int>("Resort_No")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResortId");

                    b.ToTable("ResortNos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ResortId = 1,
                            Resort_No = 101
                        },
                        new
                        {
                            Id = 2,
                            ResortId = 1,
                            Resort_No = 102
                        },
                        new
                        {
                            Id = 3,
                            ResortId = 1,
                            Resort_No = 103
                        },
                        new
                        {
                            Id = 4,
                            ResortId = 1,
                            Resort_No = 104
                        },
                        new
                        {
                            Id = 5,
                            ResortId = 2,
                            Resort_No = 201
                        },
                        new
                        {
                            Id = 6,
                            ResortId = 2,
                            Resort_No = 202
                        },
                        new
                        {
                            Id = 7,
                            ResortId = 2,
                            Resort_No = 203
                        });
                });

            modelBuilder.Entity("ParadisePlanner.Domain.Entities.ResortNo", b =>
                {
                    b.HasOne("ParadisePlanner.Domain.Entities.Resort", "Resorts")
                        .WithMany()
                        .HasForeignKey("ResortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resorts");
                });
#pragma warning restore 612, 618
        }
    }
}
